#ifndef TFPF_POINTS_TABLE_PROJECTOR_SRC_INCLUDE_FIXTURE_HH_
#define TFPF_POINTS_TABLE_PROJECTOR_SRC_INCLUDE_FIXTURE_HH_

struct Fixture
{
};

#endif  // TFPF_POINTS_TABLE_PROJECTOR_SRC_INCLUDE_FIXTURE_HH_
