name: style
on: [push, workflow_dispatch]

jobs:
  style:
    name: style in ${{ matrix.path }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        path: ['src/include', 'src/lib']
    steps:
      - uses: actions/checkout@v4
      - uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '14'
          check-path: ${{ matrix.path }}
