name: style
on: [push, workflow_dispatch]

jobs:
  style:
    name: style
    runs-on: ubuntu-22.04
    steps:
      - uses: apt install clang-format-14
      - uses: actions/checkout@v4
      - run: clang-format --dry-run -Werror src/include/*.hh src/lib/*.cc
