name: test
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          make -j CC=g++13
          ./project examples/cricket_world_cup_2023.txt >> output.txt
          ./project examples/fruits.txt >> output.txt
          ./project examples/indian_premier_league_2024.txt >> output.txt
          ./project examples/womens_premier_league_2024.txt >> output.txt
          [ $(sha256sum output.txt | awk '{print $1}') = 36ccfd591868a4a26871f82755b95fb735417c0929ec01658a51dd6fa34fd2f4 ] && echo OK
